name: Build

on: push

jobs:
  build:
    if:
      contains(github.event.pull_request.user.login, 'renovate') != 'true' &&
      contains(github.actor, 'renovate') != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and commit build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm install --frozen-lockfile
          npm run build
          git add dist/
          git diff-index --quiet HEAD || git commit -m "ci: generate build"
          git push
