name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    if:
      contains(github.event.pull_request.user.login, 'renovate') != 'true' &&
      contains(github.actor, 'renovate') != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
