name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    if:
      contains(github.event.pull_request.user.login, 'renovate') != 'true' &&
      contains(github.actor, 'renovate') != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@main
        with:
          title-regex: "#[eE][xX]-[0-9]+"
          on-failed-regex-fail-action: false
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
